In [19]:
import matplotlib.pyplot as plt
from PIL import Image
import cv2
import imutils
import matplotlib.pyplot as plt
import numpy as np
import functools
from skimage.feature import local_binary_pattern


In [20]:
radius = 2
n_points = 8 * radius

In [21]:
def Preprocessing (image) : 
    image = cv2.cvtColor(image,cv2.COLOR_RGB2GRAY)
    height, width = image.shape
    img = cv2.GaussianBlur(image, (9, 9), 0) #decrease noise for dialation
    img = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV, 101, 30)
    image = cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV, 101, 30)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15, 20))
    img = cv2.dilate(img, kernel, iterations=8)
    contours = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)[0] 
    biggest_contour = functools.reduce(lambda c1, c2: c1 if cv2.contourArea(c1) > cv2.contourArea(c2) else c2,contours) #find the biggest contour for text area
    x, y, w, h = cv2.boundingRect(biggest_contour) # find smallest rect that can contain the text area after dialation
    image = image[y:y + h, x:x + w]
    return image


In [25]:
image = cv2.imread("..\\Data_split\\train\\Females\\F3.jpg")
img = Preprocessing(image)
#LBP looks at points surrounding a central point
#and tests whether the surrounding points are greater than or less than the central point
#The histogram of the LBP result is a good measure to classify textures
#n_points: Number of circularly symmetric neighbor set points 
#radius: Radius of circle
#nri_uniform (method): non rotation-invariant uniform patterns variant which is only gray scale invariant (try it to increase accuracy only)
lbp = local_binary_pattern(img, n_points, radius, method='nri_uniform')
#Number of bins of histogram
n_bins = n_points * (n_points - 1) + 3
lbp_hist = np.histogram(lbp.ravel(), bins=np.arange(n_bins + 1), density=True)[0]
#lbp_normalized = np.linalg.norm(lbp_hist)
print(lbp)



[[241. 241. 241. ... 241. 241. 241.]
 [241. 241. 241. ... 241. 241. 241.]
 [241. 241. 241. ... 241. 241. 241.]
 ...
 [241. 241. 241. ... 241. 241. 241.]
 [241. 241. 241. ... 241. 241. 241.]
 [241. 241. 241. ... 241. 241. 241.]]
